FROM node
WORKDIR /app
COPY frontend-example-docker /app


EXPOSE 5000
RUN npm install -g serve
RUN npm install

ENV API_URL=http://192.168.100.126:8000
RUN npm run build

CMD ["serve", "-s", "-l", "5000", "dist"]