version: '3.3' 

services: 
  backend: 
    image: backend
    build:
      context: ../
      dockerfile: ./2.9/Dockerfile-backend2
    ports: 
      - 8000:8000
    environment: 
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - DB_USERNAME=devopswithdocker
      - DB_PASSWORD=example
      - DB_HOST=postgres
    volumes: 
      - ./logs.txt:/app/logs.txt
    container_name: backend
    depends_on: 
      - redis
      - postgres

  frontend: 
    image: frontend
    build:
      context: ../
      dockerfile: 2.9/Dockerfile-frontend
    ports: 
      - 5000:5000
    environment: 
      - API_URL=/api
    container_name: frontend
    depends_on: 
      - backend

  redis:
    image: redis
    restart: unless-stopped
    container_name: redis

  postgres:
    image: postgres
    restart: unless-stopped
    environment: 
      - POSTGRES_USER=devopswithdocker
      - POSTGRES_PASSWORD=example
    container_name: postgres

    volumes:
      - database:/var/lib/postgresql/data
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on: 
      - frontend
      - backend
volumes: 
  database: