FROM ubuntu

RUN apt update
RUN apt install -y curl git > /dev/null 2>&1
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt install -y nodejs > /dev/null 2>&1
RUN git clone https://github.com/docker-hy/backend-example-docker
RUN mv ./backend-example-docker ./app
WORKDIR ./app

RUN npm install
CMD ["npm", "start"]