version: '3.3' 

services: 
  ml-backend: 
    image: ml-backend
    build:
      context: ./ml-kurkkumopo-backend
      dockerfile: ./Dockerfile
    ports: 
      - 5000:5000
    volumes:
      - model:/src/model
    container_name: ml-backend
    depends_on:
      - ml-training

  ml-frontend: 
    image: ml-frontend
    build:
      context: ./ml-kurkkumopo-frontend
      dockerfile: ./Dockerfile
    ports: 
      - 3000:3000
    environment: 
      - API_URL=http://colasloth.com:8000
    container_name: ml-frontend
    depends_on:
      - ml-training
      - ml-backend

  ml-training: 
    image: ml-training
    build:
      context: ./ml-kurkkumopo-training
      dockerfile: ./Dockerfile
    volumes:
      - model:/src/model
      - imgs:/src/imgs
      - data:/src/data
    container_name: ml-training

volumes: 
  model:
  imgs:
  data: